CREATE TABLE stock_member(
 email VARCHAR2(100) PRIMARY KEY,
 pwd VARCHAR2(20) NOT NULL,
 name VARCHAR2(50) NOT NULL,
 gender VARCHAR2(10) NOT NULL,
 birth VARCHAR2(20) NOT NULL,
 tell  VARCHAR2(20) NOT NULL,
 favorite VARCHAR2(2000) NOT NULL
);